# Generated by Django 2.1.7 on 2019-06-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_graduation_diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archieving_history',
            name='history_lecture_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='archieving_history',
            name='history_subject_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='archieving_history',
            name='history_subject_complete_division',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='archieving_history',
            name='history_subject_name',
            field=models.CharField(max_length=50),
        ),
    ]
