# Generated by Django 2.1.7 on 2019-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_graduation_diagnosis', '0002_auto_20190624_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='graduation_rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_university_name', models.CharField(max_length=50)),
                ('rule_department_code', models.CharField(max_length=50)),
                ('rule_name', models.CharField(max_length=50)),
                ('rule_track', models.CharField(default='자동', max_length=50)),
                ('rule_type', models.CharField(default='0', max_length=10)),
                ('rule_value', models.CharField(default='0', max_length=50)),
                ('rule_division', models.CharField(max_length=30)),
            ],
        ),
    ]
