# Generated by Django 2.1.7 on 2019-06-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_graduation_diagnosis', '0003_graduation_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation_rule',
            name='rule_admission_year',
            field=models.CharField(default=2012, max_length=20),
            preserve_default=False,
        ),
    ]
