# Generated by Django 2.1.7 on 2019-06-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_graduation_diagnosis', '0004_graduation_rule_rule_admission_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduation_rule',
            old_name='rule_division',
            new_name='rule_subject_group',
        ),
    ]
