# Generated by Django 2.1.5 on 2019-06-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=20)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=20)),
                ('subject_complete_division', models.CharField(max_length=20)),
                ('subject_area', models.CharField(max_length=20)),
                ('subject_credit', models.CharField(max_length=20)),
                ('subject_assessment_Methods', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='departmentinfo',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_common_data.UniversityInfo'),
        ),
    ]
