# Generated by Django 2.1.7 on 2019-06-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_archiving_history', '0002_auto_20190620_1045'),
        ('app_common_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectinfo',
            name='university',
        ),
        migrations.RenameField(
            model_name='metadatainfo',
            old_name='subdata_presence_yn',
            new_name='upper_data_presence_yn',
        ),
        migrations.DeleteModel(
            name='SubjectInfo',
        ),
    ]
