# Generated by Django 2.1.7 on 2019-06-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completiondivision',
            old_name='Division_name',
            new_name='division_name',
        ),
        migrations.RenameField(
            model_name='subjectdomain',
            old_name='Domain_name',
            new_name='domain_name',
        ),
    ]
