# Generated by Django 2.1.7 on 2019-06-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadatainfo',
            name='upper_data_presence_yn',
        ),
        migrations.AddField(
            model_name='metadatainfo',
            name='upper_data_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='metadatainfo',
            name='meta_data_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metadatainfo',
            name='meta_data_creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='metadatainfo',
            name='meta_data_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metadatainfo',
            name='meta_data_relation_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metadatainfo',
            name='meta_data_relation_name',
            field=models.CharField(max_length=50),
        ),
    ]
