# Generated by Django 2.1.7 on 2019-06-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common_data', '0002_auto_20190620_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadatainfo',
            name='meta_data_creation_date',
        ),
    ]
