# Generated by Django 2.1.7 on 2019-06-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common_data', '0003_remove_metadatainfo_meta_data_creation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeInfo',
        ),
        migrations.RemoveField(
            model_name='completiondivision',
            name='university',
        ),
        migrations.RemoveField(
            model_name='departmentinfo',
            name='university',
        ),
        migrations.RemoveField(
            model_name='subjectdomain',
            name='university',
        ),
        migrations.DeleteModel(
            name='CompletionDivision',
        ),
        migrations.DeleteModel(
            name='DepartmentInfo',
        ),
        migrations.DeleteModel(
            name='SubjectDomain',
        ),
        migrations.DeleteModel(
            name='UniversityInfo',
        ),
    ]
