# Generated by Django 2.1.5 on 2019-06-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='archving_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_user_id', models.CharField(max_length=20)),
                ('history_subject_code', models.CharField(max_length=20)),
                ('history_lecture_code', models.CharField(max_length=20)),
                ('history_subject_name', models.CharField(max_length=20)),
                ('history_subject_complete_division', models.CharField(max_length=20)),
                ('history_subject_area', models.CharField(max_length=20)),
                ('history_subject_credit', models.CharField(max_length=20)),
                ('history_subject_assessment_Methods', models.CharField(max_length=20)),
            ],
        ),
    ]
