# Generated by Django 2.1.7 on 2019-06-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_common_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='archieving_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_user_id', models.CharField(max_length=20)),
                ('history_lecture_code', models.CharField(max_length=20)),
                ('history_subject_name', models.CharField(max_length=20)),
                ('history_subject_complete_division', models.CharField(max_length=20)),
                ('history_subject_area', models.CharField(max_length=20)),
                ('history_subject_credit', models.CharField(max_length=20)),
                ('history_subject_assessment_Methods', models.CharField(max_length=20)),
                ('history_student_grade', models.CharField(max_length=20)),
                ('history_grade_year', models.CharField(max_length=20)),
                ('history_semester', models.CharField(max_length=20)),
                ('history_subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_common_data.SubjectInfo')),
            ],
        ),
    ]
