# Generated by Django 2.1.7 on 2019-06-17 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_archiving_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archieving_history',
            name='history_user_id',
        ),
        migrations.AddField(
            model_name='archieving_history',
            name='history_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
