# Generated by Django 2.1.7 on 2019-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_archiving_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archieving_history',
            name='history_subject_code',
            field=models.CharField(max_length=20),
        ),
    ]
