# Generated by Django 2.1.7 on 2019-06-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_archiving_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archieving_history',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='archieving_history',
        ),
    ]
