# Generated by Django 2.1.7 on 2019-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.CharField(max_length=20)),
                ('lecture_subject_code', models.CharField(max_length=20)),
                ('lecture_subject_name', models.CharField(max_length=20)),
                ('lecture_professor_name', models.CharField(max_length=20)),
                ('lecture_place', models.CharField(max_length=20)),
                ('lecture_week_expression', models.CharField(max_length=20)),
                ('lecture_star_time', models.CharField(max_length=20)),
                ('lecture_end_time', models.CharField(max_length=20)),
                ('lecture_opened_year', models.CharField(max_length=20)),
                ('lecture_opened_semester', models.CharField(max_length=20)),
                ('lecture_opened_department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=20)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=20)),
                ('subject_completion_division', models.CharField(max_length=20)),
                ('subject_area', models.CharField(blank=True, max_length=20)),
                ('subject_credit', models.FloatField()),
            ],
        ),
    ]
