# Generated by Django 2.1.5 on 2019-06-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_university_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_opened_department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_opened_semester',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_opened_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_professor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_star_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_subject_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_subject_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturecalendar',
            name='lecture_week_expression',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='subject_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='subject_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='subject_completion_division',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='subject_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectinfo',
            name='university_name',
            field=models.CharField(max_length=50),
        ),
    ]
