# Generated by Django 2.1.5 on 2019-06-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_university_data', '0002_auto_20190621_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectinfo',
            name='subject_credit',
            field=models.CharField(max_length=50),
        ),
    ]
