# Generated by Django 2.1.5 on 2019-04-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDumpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NO', models.CharField(max_length=20)),
                ('년도', models.CharField(max_length=20)),
                ('학기', models.CharField(max_length=20)),
                ('개설대학', models.CharField(max_length=20)),
                ('개설학과전공', models.CharField(max_length=20)),
                ('학수번호', models.CharField(max_length=20)),
                ('분반', models.CharField(max_length=20)),
                ('교과목명', models.CharField(max_length=20)),
                ('이수구분', models.CharField(max_length=20)),
                ('선택영역', models.CharField(max_length=20)),
                ('학년', models.CharField(max_length=20)),
                ('학점', models.CharField(max_length=20)),
                ('이론', models.CharField(max_length=20)),
                ('실습', models.CharField(max_length=20)),
                ('수강인원', models.CharField(max_length=20)),
                ('요일및강의시간', models.CharField(max_length=20)),
                ('강의실', models.CharField(max_length=20)),
                ('교수명', models.CharField(max_length=20)),
                ('수강대상및유의사항', models.CharField(max_length=20)),
                ('사이버강좌', models.CharField(max_length=20)),
                ('강의언어', models.CharField(max_length=20)),
                ('수업유형', models.CharField(max_length=20)),
                ('수강제한', models.CharField(max_length=20)),
                ('강의평가유형', models.CharField(max_length=20)),
                ('강사료', models.CharField(max_length=20)),
                ('메인교수소속', models.CharField(max_length=20)),
                ('이번교수명', models.CharField(max_length=20)),
                ('이번교수소속', models.CharField(max_length=20)),
                ('삼번교수명', models.CharField(max_length=20)),
                ('삼번교수소속', models.CharField(max_length=20)),
                ('주관학과', models.CharField(max_length=20)),
                ('강의실수용인원', models.CharField(max_length=20)),
                ('관심과목등록수', models.CharField(max_length=20)),
                ('외국인전용', models.CharField(max_length=20)),
                ('내국인전용', models.CharField(max_length=20)),
            ],
        ),
    ]
