# Generated by Django 2.1.5 on 2019-04-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data_conversion', '0003_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='가',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='나',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='다',
            new_name='c',
        ),
    ]
