# Generated by Django 2.1.7 on 2019-06-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_course_design', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LectureCalendar',
        ),
    ]
